---
title: 'Project 1: Exploratory Analysis'
author: "Jaxon Bowman"
date: '2019-12-15'
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r, include=FALSE}
#install.packages("dplyr")
#install.packages("tidyverse")
#install.packages("tidyr")
#install.packages("ggplot2")
library(dplyr)
library(tidyverse)
library(tidyr)
library(ggplot2)
```


## Project 1: Exploratory Analysis
## Introduction:
For this project, I choose to combine three datasets by the variable, country. The first dataset I choose was about Global Plastic Waste, and I obtained it from GitHub's #tidytuesday project. This dataset includes the per capita mismanaged plastic waste, GDP per capita, country, country code, year, and total population. I choose this dataset because I am interested in sustainability and the environment, and I thought it would be facinating to observe the varying mismanaged waste among countries. The next dataset I choose was about the Sanitation Percents for varying countries. I got this dataset from "The World Bank- Data Bank/World Development Indicators". This dataset included the percentages of Urban Populations using basic sanitation services for different countries in the year 2010. As I am interested in global health and medicine, this dataset stood out to me. I thought it would be interesting to compare Sanitation Percentages to Plastic Waste and GDP per capita. Lastly, I included one more dataset that about which countries have laws regarding equal pay for different genders and which countries do not have these kinds of laws. Again, I got this dataset from "The World Bank-DataBank World Development Indicators." I choose to add this one in because I am interested in women's rights and because I wanted to include a non-numerical column in the combined datasets. The second and third datasets were both from the year 2010, and I selected to only use the year 2010 from the first dataset. From this data, I would expect there to be an association between Sanitation Percent and GDP per capita, with them being positively correlated. Also I am expecting there to be an association between Plastic Waste and Sanitation Percent, with them possibly being negatively correlated. It could be possible that more developed countries with greater Sanitation Percents have more mismanaged waste. 

 
## 1. Tidying: Rearranging Wide/Long 
```{R}
#1 Tidying
mismanaged_vs_gdp <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/per-capita-mismanaged-plastic-waste-vs-gdp-per-capita.csv")

SAN2<- read.csv("/Users/jaxonbowman/Desktop/website/content/SanitationData.csv")
LAW2 <-read.csv("/Users/jaxonbowman/Desktop/website/content/lawre.csv")
nonawaste<-mismanaged_vs_gdp%>%na.omit()%>%glimpse()
names(nonawaste)[4]<- "waste"
names(nonawaste)[5]<-"gdp"
names(nonawaste)[6]<-"pop"

nonawaste2<-nonawaste%>%select(-"Entity",-"gdp",-"pop")%>%glimpse()
untidywaste2<-nonawaste2%>%pivot_wider(names_from = Code, values_from = waste)%>%head()
tidywaste2<-untidywaste2%>%pivot_longer(2:146,names_to="Code", values_to ="waste")%>%glimpse()


```
To begin, each of my data sets were already tidy other than me needing to delete a few extraneous columns. So, to demostrate my tidying skills, I used pivot_wider on the mismanaged_vs_gdp dataset to reshape the dataset from long to wide. I first removed a few columns and then used pivot_wider with names_from= Code, and values_from= waste to make an extra long dataset. I named this dataset "untidywaste2". Next, I used pivot_longer to tidy the dataset. I named the newly tidy dataset "tidywaste2". 

## 2. Joining/Merging

```{R}

SAN <- SAN2%>%select(-"Series.Name", -"Series.Code")%>%glimpse()
names(SAN)[1]<-"Country Name"
names(SAN)[2]<-"Country Code"
names(SAN)[3]<-"Sanitation Percent"

LAW <-LAW2%>%select(-"Series.Name", -"Series.Code", -"Country.Code")%>%glimpse()
names(LAW)[1]<-"Country Name"
names(LAW)[2]<-"Equal gender pay (0=NO, 1=YES)"

plasticgdp <-mismanaged_vs_gdp%>%select(-"Code")%>%glimpse()
plasticgdp2 <-plasticgdp%>%filter(Year=="2010")%>%glimpse()
names(plasticgdp2)[1]<-"Country Name"
sang <-SAN %>%na.omit()%>%glimpse()
plasticg<-plasticgdp2%>%na.omit()%>%glimpse()
lawg <-LAW%>%na.omit()%>%glimpse()

jointdata<-sang %>%inner_join(plasticg, by="Country Name")%>%glimpse()
alldata<-jointdata%>%inner_join(lawg, by="Country Name")%>%glimpse()
head(alldata)

```
In the process of joining the datasets, I first had to delete extraneous columns that appears in some of the datasets. To begin, I deleted "Series Name" and "Series Code" from the Sanitation dataset using the filter function. Next, I deleted "Series Name", "Series Code", and "Country Code" from the Law about equal gender pay dataset. Finally, I deleted "Code" from the mismanaged plastic dataset. After cleaning these datasets up and getting rid of the NAs, I joined them using  inner_join. I first joined the mismanaged plastic waste dataset to the sanitation dataset and then I joined the law dataset to that one and I named it "alldata". I choose to use inner_join because it drops any rows in either dataset without a match, only keeping rows that have a match on the ID variables. I joined the three datasets by "Country Name". Another reason I choose inner_join was so that no additonal NAs would be introduced and the results would contain the number of rows equal to the intersection of IDs. 114 cases were dropped during the process of first joining the Sanitation Data to the Mismanaged Plastic Waste Data. These cases were dropped as they did not have values for each column in the newly combined dataset called "alldata" and inner_join does not introduce and NAs. When that new dataset "joindata" with Laws regarding equal gender pay dataset, 2 cases were dropped. Again, these three cases were countries that did not match up with the newly combined dataset.

## 3. Wrangling

```{R}
#Wrangling
names(alldata)[5] <- "Plastic Waste (kg/person/day)"
names(alldata)[6]<- "GDP per capita"
names(alldata)[7]<- "Population"
names(alldata)[8]<- "Law for equal gender pay (0=NO, 1=YES)"
alldata1 <-alldata%>% mutate(GDP=`GDP per capita`*Population)%>%glimpse()
alldata1%>%arrange(desc(`Sanitation Percent`))%>%glimpse()
alldata1%>%arrange(`Sanitation Percent`)%>%glimpse()
alldata1%>%arrange(desc(GDP))%>%glimpse()
alldata1%>% arrange(desc(`GDP per capita`))%>%glimpse()
alldata1%>%arrange(`GDP`)%>%glimpse()
alldata1%>% summarize(mean(`Plastic Waste (kg/person/day)`))%>%glimpse()
alldata1%>%summarize(mean(`Sanitation Percent`))%>%glimpse()
highwaste <- alldata1%>%filter(`Plastic Waste (kg/person/day)` > 0.0533)%>%glimpse()
lowwaste <-alldata1%>%filter(`Plastic Waste (kg/person/day)` < 0.0533)%>%glimpse()
highwaste %>%group_by(`Law for equal gender pay (0=NO, 1=YES)`)%>%summarize(mean_gdpcap=mean(`GDP per capita`, na.rm = T))%>%glimpse()
alldata1%>%group_by(`Law for equal gender pay (0=NO, 1=YES)`)%>%summarize(mean_gdp=mean(GDP, na.rm= T))%>%glimpse()
alldata1%>%group_by(`Law for equal gender pay (0=NO, 1=YES)`)%>%summarize(mean_gdpC=mean(`GDP per capita`, na.rm = T))%>%glimpse()
alldata1%>%group_by(`Law for equal gender pay (0=NO, 1=YES)`)%>%summarize(meansanp=mean(`Sanitation Percent`, na.rm = T))%>%glimpse()
alldata1%>%group_by(`Law for equal gender pay (0=NO, 1=YES)`)%>%summarize(sdsanp=sd(`Sanitation Percent`, na.rm = T))%>%glimpse()
alldata1%>%summarize(mean(`GDP per capita`))%>%glimpse()
alldata1%>%summarize(mean(`GDP`))%>%glimpse()
pt1all<-alldata1%>%select(`Country Name`, `Sanitation Percent`, `GDP per capita`)%>%glimpse()
head(pt1all)


```
Next, I generated several summary statistics. I used arrange(desc()) to find that Isreal, New Zealand, and Singapore all had the highest Sanitation Percents in 2010, with 100% of Urban Populations having at least basic Sanitation services.Next, I used arrange() to find that Madagascar had the lowest Sanitation percent in 2010, with 14.1% of Urban Populations having basic sanitation services.Following that, I mutated the dataset using the mutate() function to make a new column with the GDP which was the GDP per capita times the population. I then used arrange again to find that The US had the highest GDP in 2010, followed by China and then India. However, Singapore had the highest GDP per capita in 2010, followed by Norway and then the US. Next, I used summarize() to calculate that the mean plastic waste in 2010 was 0.0533 kg/person/day. I also found that the mean Sanitation Percent was 78.84% for the countries in the dataset. After I found the mean plastic waste, I used filter() to filter all of the countries with plastic waste greater than the mean, and I named this new dataset highwaste. There were 37 countries in 2010 with higher plastic waste than the mean plastic waste (kg/person/year).There were 72 countries in 2010 with lower plastic wastes than the mean. In continuation, I used group_by() to group by 'Law for equal pay' along with summarize to find that the mean gdp per capital for countries that have plastic was higher than the mean plastic waste was 6815.625 for countries without laws for equal gender pay, and 7531.124 for countries with laws for equal gender pay. Suprisingly, countries with no laws regarding equal gender pay had a high mean GDP than countries with laws for equal gender pay. The countries without laws for equal gender pay had a mean gdp of 7.8e11, compared to 4.3e11 of the countries with laws for equal gender pay. I used group_by and summarize again to find that the mean GDP per capita for countries without laws for equal gender pay was 11138.25 and the mean GDP per capita for countries with laws for equal gender pay was 22757.81. Next, I found that the mean Sanitation Percent was 75.39% for countries that did not have laws for equal gender pay. I also found that the mean Sanitation Percent for countries with laws for equal gender pay was 84.35%, which is 9% higher. The standard deviation for both of these groups was 24.66 and 24.23 respectively. Another summary statistic I found was that the mean GDP per capita for all of the countries was 15615.51 amd the mean GDP was 6.5e11. 

## 4. Visualizing
```{R}

names(alldata1)[3]<-"SanitationPercent"
names(alldata1)[5]<-"PlasticWaste"
names(alldata1)[6]<-"GDPpercapita"
names(alldata1)[8]<-"GenderLaw"
names(alldata1)[1]<-"CountryName"
names(alldata1)[2]<-"CountryCode"
head(alldata1)

names(pt1all)[1]<-"CountryName"
names(pt1all)[2]<-"SanitationPercent"
names(pt1all)[3]<-"GDPpercapita"

plot1<-ggplot(data=alldata1, aes(x= SanitationPercent, y=GDPpercapita, color=GenderLaw)) + geom_point(size=2, alpha=0.85) +scale_color_gradient(low="blue", high = "red")
plot1+ ggtitle("GDP per Capita by Sanitation Percent and Gender Law")+ ylab("GDP per capita")+ xlab("Sanitation Percent")+theme_minimal()+ scale_y_continuous(breaks=c(10000,20000,30000,40000,50000,60000,70000,80000))+ guides(fill=guide_legend(title="Equal Pay for Gender Law Status 0=NO, 1=YES"))

alldata1%>%arrange(desc(`SanitationPercent`))%>%glimpse()
cleandata<-alldata1%>%filter(SanitationPercent>99.5)%>%glimpse()

plot2<-ggplot(cleandata, aes(x=CountryName, y=GDPpercapita, fill=GenderLaw))+geom_bar(stat="summary", fun.y="mean", color="blue")+coord_flip()
plot2+ ggtitle("Mean GDP per Capita for Top 10 Sanitation Countries")+ ylab("GDP per capita")+ xlab("Country Name")+theme(axis.text.x=element_text(angle= 45, hjust = 1))+theme(legend.background = element_rect(fill="lightpink"))+ guides(fill=guide_legend(title="Equal Pay for Gender Law Status 0=NO, 1=YES"))+theme_light()

```

The first plots describes Sanitation Percent by GDP per capita and whether or not the country has laws regarding equal pay for gender. In the graph, it appears that as the Sanitation Percent increases, the GDP per capita increases as well suggesting that there is a possible positive correlation between GDP per capital and Sanitation Percent. The color of the points desribes whether or not there is a law regarding equal pay for each gender. Observing this graph, it appears that the red points are typically higher on the graph than the blue and are more to the right, indicating that countries with laws about equal pay for gender typically have both higher GDP per capita and higher Sanitation Percentages. I made this plot using ggplot and geom_point. I changed the tick marks on the y-axis for this graph, along with the size and color of the of the points. 

The second plot illustrates the GDP per capita by country for the top 10 countries with the highest sanitation percentages. I first used the function arrange(desc()) to arrange by Sanitation Percent and then used the filter() function to only use the top 10 countries with the highest sanitation. I then saved this as a new dataset called cleandata. Overall, this graph looks at how the top 10 countries sanitation percentage wise, different in GDP per capita, and also shows whether or not each of the 10 countries has laws regarding equal pay for each gender. This graph suggests that Singapore has the highest GDP per capita out of the countries with the highest sanitation percentages. This graph also shows that 6 out of the top 10 countries with the highest sanitation percentages have a law regarding equal pay for each gender. 

##5. Dimensionality Reduction
```{R}

alldata2<-alldata1%>%select(-"CountryName",-"CountryCode",-"Year", -"PlasticWaste",-"Population",-"GenderLaw",-"GDP")%>%glimpse()
alldata3<-alldata1%>%select(-"CountryName",-"CountryCode",-"Year", -"SanitationPercent",-"Population",-"GenderLaw",-"GDP")%>%glimpse()
alldata4<-alldata1%>%select(-"CountryName",-"CountryCode",-"Year", -"GDPpercapita",-"Population",-"GenderLaw",-"GDP")%>%glimpse()
#Sanitation Percent and GDP per Capita
wss<-vector()
for(i in 1:10){
temp<-alldata2%>%dplyr::select(SanitationPercent,GDPpercapita)%>%kmeans(.,i)
wss[i]<-temp$tot.withinss%>%glimpse()
}
ggplot()+geom_point(aes(x=1:10,y=wss))+geom_path(aes(x=1:10,y=wss))+
 xlab("clusters")+scale_x_continuous(breaks=1:10)

kmeans1<-alldata2%>%scale%>%kmeans(2)%>%glimpse
kmeans1

kmeansclust<-alldata2%>%mutate(cluster=as.factor(kmeans1$cluster))%>%glimpse
kmeansclust%>%ggplot(aes(SanitationPercent,GDPpercapita,color=cluster))+geom_point()

kmeans1$betweenss
kmeans1$size
kmeans1$tot.withinss
kmeans1$centers

#GDP per capita and Plastic Waste
wss2<-vector()
for(i in 1:10){
temp3<-alldata3%>%dplyr::select(GDPpercapita,PlasticWaste)%>%kmeans(.,i)
wss2[i]<-temp3$tot.withinss%>%glimpse()
}
ggplot()+geom_point(aes(x=1:10,y=wss2))+geom_path(aes(x=1:10,y=wss2))+
 xlab("clusters")+scale_x_continuous(breaks=1:10)

kmeans2<-alldata3%>%scale%>%kmeans(2)%>%glimpse
kmeans2

kmeans2$betweenss
kmeans2$size
kmeans2$centers
kmeansclust2<-alldata3%>%mutate(cluster=as.factor(kmeans2$cluster))%>%glimpse
kmeansclust2%>%ggplot(aes(GDPpercapita,PlasticWaste,color=cluster))+geom_point()

#Sanitation and Plastic Waste

wss3<-vector()
for(i in 1:10){
temp4<-alldata4%>%dplyr::select(SanitationPercent,PlasticWaste)%>%kmeans(.,i)
wss3[i]<-temp4$tot.withinss%>%glimpse()
}
ggplot()+geom_point(aes(x=1:10,y=wss3))+geom_path(aes(x=1:10,y=wss3))+
 xlab("clusters")+scale_x_continuous(breaks=1:10)
kmeans5<-alldata4%>%scale%>%kmeans(2)%>%glimpse()
kmeans5
kmeans5$size
kmeans5$betweenss
kmeans5$tot.withinss

kmeansclust5<-alldata4%>%mutate(cluster=as.factor(kmeans5$cluster))
kmeansclust5%>%ggplot(aes(SanitationPercent,PlasticWaste,color=cluster))+geom_point()
```
For my data, I performed a k-means cluster for multiple variables in my dataset. The first k-means cluster I performed was for Sanitation Percent and GDP per capita. Initially, I made a new dataset from my joint data, called "alldata2". Next, I determined the number of clusters by observed the plot of I made for clusters vs. wss. I determined the number of clusters to be 2 by looking at the elbow of the graph I generated. 2 was where graph started to decrease gradually. Next, using k-means cluster, I was able to make a plot using ggplot. I am able to observe two clear groups, from this I can see that countries with a high GDP almost always have a high sanitation. From this plot, it is also clear that countries with a Sanitation Percent less than arond 75%, almost always have lower GDP. The two clusters in this plot are seen as high GDP per capita  + high Sanitation, and low GDP per capita with low Sanitation. The betweenss was 117.28. The size of the clusters was 78 and 31, with the group having higher Sanitation Percents and GDP per capita containing 78 countries. 

Next, performed a second k-means cluster for GDP per capita and unmanaged plastic waste. The first thing I did was find out how many clusters to use based to the plot that I generated of clusters vs. wss. I again determined the number of cluster to be 2. Next, I made a plot using ggplot visualizing the points for both clusters. From this plot, it can be observed that there are 2 clusters, separating higher and lower GDP per capita. The group with higher GDP per capita has overall lower Plastic Waste. Using k-means cluster, I determined the size of each cluster to be 77 and 32. The betweenss was 106.58. 

Finally, I performed a third k-means cluster for Sanitation and Plastic Waste. I determined the number of clusters to be 2 by observing the clusters vs. wss plot. Then, I ploted the clusters and  able to observed 2 distinct groups. Using, k-means cluster, the plot that was produced separated the two groups on the basis of high and low plastic waste, but the distinction between Sanitation Percents was not as clear in this plot. The size of the 2 clusters was 97 and 12 with the group with lower Plastic Waste containing 97 countries. The betweenss was 67.5 and the tot.withinss was 148.5. 
